zookeeper:
    image: 2679/zookeeper:3.4.6
    ports:
     - '2181:2181'

kafka:
    image: 2679/kafka:0.9.0.1
    ports: 
     - '9092:9092'
    links:
     - zookeeper 
    hostname: kafka 
    volumes:
     - ../flink-beam-eventime-processing:/kafka/flink-beam-eventime-processing
    environment:
     - ADVERTISED_HOST_NAME=kafka 
     - KAFKA_CREATE_TOPICS="results:1:1, sources:1:1"

jobmanager:
    image: 2679/flink:latest
    ports: 
     - '6123:6123'
     - '8081:8081'
    hostname: jobmanager
    command: jobmanager 
    links:
     - zookeeper
     - kafka
    environment:
     - JOB_MANAGER_RPC_ADDRESS=jobmanager 

taskmanager:
    image: 2679/flink:latest
    command: taskmanager 
    volumes:
     - ../flink-beam-eventime-processing/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
     - ../flink-beam-eventime-processing/checkpoint:/opt/flink/checkpoint
    links:
     - jobmanager
     - zookeeper
     - kafka 
    environment:
     - JOB_MANAGER_RPC_ADDRESS=jobmanager 
     
     